
package soap.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://soap.webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addition", targetNamespace = "http://soap.webservices/", className = "soap.webservices.Addition")
    @ResponseWrapper(localName = "additionResponse", targetNamespace = "http://soap.webservices/", className = "soap.webservices.AdditionResponse")
    @Action(input = "http://soap.webservices/Calculator/additionRequest", output = "http://soap.webservices/Calculator/additionResponse")
    public String addition(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplication", targetNamespace = "http://soap.webservices/", className = "soap.webservices.Multiplication")
    @ResponseWrapper(localName = "multiplicationResponse", targetNamespace = "http://soap.webservices/", className = "soap.webservices.MultiplicationResponse")
    @Action(input = "http://soap.webservices/Calculator/multiplicationRequest", output = "http://soap.webservices/Calculator/multiplicationResponse")
    public String multiplication(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

}
